### ISSUE TITLE
浏览历史有条数限制？

### ISSUE THREAD

**Issue by hwdef** [Ehco1996/dig-up#1]
看了知乎上写的实现原理，会对比浏览历史，不过b站的浏览历史好像不是全部的，可能一个月之前的都没有了。

**Comment by Ehco1996** [comment]
抱歉回复的比较晚
b 站的是历史流量记录貌似是一直保持的？我这里测下来是的，因为 b 站有个自动定位视频开头的的功能就是通过历史记录做的

**Comment by hwdef** [comment]
那有可能是我记错了。
